## Vídeo 4.1 - Valores em um intervalo

In [ ]:
np.random.randint(low=40,high=100,size=100)

array([52, 98, 87, 54, 43, 92, 54, 71, 75, 60, 84, 84, 92, 76, 98, 77, 69,
       49, 45, 73, 56, 73, 67, 58, 43, 92, 70, 69, 69, 84, 82, 97, 59, 49,
       81, 54, 92, 77, 67, 49, 75, 83, 68, 40, 70, 52, 82, 74, 73, 43, 46,
       64, 62, 41, 86, 75, 49, 61, 87, 99, 61, 95, 79, 90, 85, 82, 62, 65,
       87, 63, 61, 42, 59, 63, 99, 58, 78, 59, 85, 43, 67, 49, 47, 49, 63,
       66, 89, 99, 58, 83, 53, 86, 73, 94, 98, 50, 63, 81, 85, 65],
      dtype=int32)

In [ ]:
coef_angulares = np.random.uniform(low=0.10,high=0.90,size=100)

In [ ]:
b

np.float64(79.64892274792834)

In [ ]:
norma = np.array([])

for i in range(100):
  norma = np.append(norma,np.linalg.norm(Moscow- (coef_angulares[i]*X+b)))

In [ ]:
norma

array([139.25278701, 122.95292155, 138.36240641, 102.69612688,
       140.43381872, 163.60836295, 153.97200321, 108.9000316 ,
       183.2160768 , 110.54234796, 125.77915386, 114.09307852,
       109.01738098, 161.39413204, 114.90663266, 146.28723887,
       190.02452953, 130.63887372, 102.39856067, 129.35681717,
       142.21073008, 178.73508034, 206.05036213, 185.30759683,
       119.32833694, 223.46220596, 145.76278893, 101.80659153,
       149.57027175, 150.18524823, 184.07050358, 151.94866943,
       108.73989439, 164.02742749, 147.30787977, 167.88274199,
       126.98072691, 104.15564602, 222.65309305, 138.96434696,
       225.45944539, 143.67862622, 170.13790053, 103.31751704,
       111.11300694, 125.08288245, 108.57328337, 168.75672198,
       183.74835928, 177.70331249, 174.7169389 , 104.84536307,
       101.83276673, 153.50394395, 104.54584933, 113.27965231,
       144.09908643, 168.21430798, 207.28313279, 164.92178705,
       108.49179241, 102.52346439, 163.58322892, 137.16

In [ ]:
coef_angulares[3]

np.float64(0.4065064396826119)

## Vídeo 4.2 - Reprodutibilidade

Números pseudoaleatórios são sequências de números gerados por algoritmos que tentam imitar o comportamento de sequências aleatórias. Eles não são verdadeiramente aleatórios, mas parecem ser aleatórios o suficiente para muitas aplicações práticas.

Os algoritmos geradores de números pseudoaleatórios geralmente iniciam com uma semente (seed), que é um número inicial que é fornecido como entrada para o algoritmo. A partir da semente, o algoritmo usa operações matemáticas para gerar uma sequência de números aparentemente aleatórios. No entanto, como o algoritmo é determinístico, a sequência de números gerada sempre será a mesma para a mesma semente.

In [ ]:
np.random.uniform(low=0.10,high=0.90,size=100)

array([0.46408827, 0.32729836, 0.80842901, 0.48452389, 0.25772439,
       0.86537924, 0.44878648, 0.74003093, 0.65431483, 0.77543487,
       0.58700421, 0.44443076, 0.59994962, 0.82768695, 0.37856694,
       0.8316672 , 0.77814441, 0.56055547, 0.37438649, 0.49508735,
       0.50131269, 0.89076198, 0.20654888, 0.51271692, 0.65570337,
       0.13389944, 0.47480687, 0.19421755, 0.12245348, 0.31641911,
       0.14472997, 0.71328788, 0.55124494, 0.12941506, 0.24675763,
       0.83219179, 0.40239828, 0.777123  , 0.56011563, 0.84387142,
       0.45356798, 0.79851428, 0.39941876, 0.64923376, 0.85221294,
       0.39798262, 0.83614656, 0.71978685, 0.15119144, 0.85345157,
       0.2555996 , 0.73696574, 0.3753082 , 0.15024016, 0.24787458,
       0.55014528, 0.78952438, 0.26003069, 0.41496526, 0.36358086,
       0.74860905, 0.86964953, 0.16516554, 0.59955577, 0.76879596,
       0.89087716, 0.52258031, 0.81078579, 0.69537533, 0.84359109,
       0.6634747 , 0.61326501, 0.21140085, 0.75032519, 0.33342

In [ ]:
np.random.seed(16)
np.random.uniform(low=0.10,high=0.90,size=100)

array([0.27863286, 0.51853067, 0.54056117, 0.13648156, 0.38858307,
       0.27846475, 0.65098093, 0.23098514, 0.15625989, 0.85280869,
       0.5509451 , 0.16239387, 0.67811241, 0.22676174, 0.30022505,
       0.3347898 , 0.65728857, 0.47141127, 0.27204971, 0.45746101,
       0.196703  , 0.83414961, 0.55315706, 0.47761545, 0.35165314,
       0.13457258, 0.70195593, 0.53461524, 0.71375234, 0.73235901,
       0.1577771 , 0.62777267, 0.14263947, 0.64801956, 0.45468077,
       0.47439692, 0.62884747, 0.65197331, 0.31066359, 0.10918315,
       0.71703556, 0.75291386, 0.21171328, 0.5624054 , 0.37253942,
       0.28577239, 0.258915  , 0.31719262, 0.88148221, 0.27234318,
       0.38512593, 0.11471996, 0.59343222, 0.28432431, 0.69388139,
       0.56740017, 0.43608284, 0.66740227, 0.87763642, 0.74803129,
       0.44452414, 0.86618288, 0.13820648, 0.68622544, 0.64053316,
       0.52160413, 0.55358996, 0.6783562 , 0.64608268, 0.73625014,
       0.19027642, 0.25933011, 0.67705538, 0.41509386, 0.37134

In [ ]:
norma = np.array([])
np.random.seed(84)
coef_angulares = np.random.uniform(low=0.10,high=0.90,size=100)

for i in range(100):
  norma = np.append(norma,np.linalg.norm(Moscow- (coef_angulares[i]*X+b)))

## Vídeo 4.3 - Salvando os resultados

In [ ]:
dados = np.column_stack([norma,coef_angulares])

In [ ]:
dados.shape

(100, 2)

In [ ]:
np.savetxt('dados.csv', dados,delimiter=',')